import { Component, OnInit } from '@angular/core';
import { PatientService } from '../../../../../services/patient.service';
import { AuthService } from '../../../../../services/auth.service';
import { PatientResponseDTO } from '../../../../../models/patient.model';
import { UserService } from '../../../../../services/user.service';

interface Consultation {
    id: number;
    date: string;
    doctorName: string;
    specialty: string;
    status: string;
    notes?: string;
    observations?: string;
}

interface Treatment {
    id: number;
    treatmentType: string;
    startDate: string;
    endDate: string;
    dosage: string;
    status: string;
}

interface Prescription {
    id: number;
    date: string;
    medication: string;
    instructions: string;
    dosage: string;
}

export interface Diagnosis {
    id?: number;
    description: string;
    type: string;
}

@Component({
    selector: 'app-medical-record',
    templateUrl: './medical-record.component.html',
    styleUrls: ['./medical-record.component.scss']
})
export class MedicalRecordComponent implements OnInit {
    patient: PatientResponseDTO | null = null;
    
    consultations: Consultation[] = [];
    treatments: Treatment[] = [];
    prescriptions: Prescription[] = [];
    diagnoses: Diagnosis[] = [];

    get recentConsultations(): Consultation[] {
        return this.consultations.slice(0, 5);
    }

    get recentPrescriptions(): Prescription[] {
        return this.prescriptions.slice(0, 1);
    }

    get recentTreatments(): Treatment[] {
        return this.treatments.slice(0, 1);
    }

    get recentDiagnoses(): Diagnosis[] {
        return this.diagnoses.slice(0, 1);
    }



    constructor(
        private patientService: PatientService,
        private authService: AuthService,
        private userService: UserService
    ) { }

    ngOnInit(): void {
        this.loadPatientData();
    }

    loadPatientData(): void {
        this.patientService.getMe().subscribe({
            next: (data) => {
                console.log('[DEBUG] Backend Patient Data via /me:', data);
                this.patient = { 
                    ...data,
                    birthDate: data?.birthDate || (data as any)?.birth_date,
                    gender: data?.gender,
                    bloodType: data?.bloodType || (data as any)?.blood_type
                } as PatientResponseDTO;
                
                this.consultations = (data?.consultations || []).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
                this.treatments = (data?.treatments || []).sort((a, b) => new Date(b.startDate).getTime() - new Date(a.startDate).getTime());
                this.prescriptions = (data?.prescriptions || []).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
                this.diagnoses = ((data as any)?.diagnoses || []).reverse();
            },
            error: (err) => {
                console.error('Error fetching patient data from /api/patients/me (401 Unauthorized or 404 Not Found)', err);
            }
        });
    }

    downloadPrescription(prescription: Prescription): void {
        const content = `
PRESCRIPTION
---------------------------
Date: ${new Date(prescription.date).toLocaleDateString()}
Medication: ${prescription.medication}
Dosage: ${prescription.dosage}
Instructions: ${prescription.instructions}
---------------------------
Generated by MediaCareAI
        `;
        const blob = new Blob([content], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `prescription_${prescription.id}.txt`;
        a.click();
        window.URL.revokeObjectURL(url);
    }

}
