import { Component, OnInit } from '@angular/core';
import { NutritionService } from '../../../../../services/nutrition.service';
import { PatientService } from '../../../../../services/patient.service';
import { AuthService } from '../../../../../services/auth.service';
import { DailyHealthReport, AnomalyType } from '../../../../../models/nutrition.model';
import { PatientResponseDTO } from '../../../../../models/patient.model';
import { LifestyleService } from '../../../../../services/lifestyle.service';
import { GoalCategory } from '../../../../../models/lifestyle.model';
import { forkJoin } from 'rxjs';

@Component({
  selector: 'app-nutrition-daily-report',
  templateUrl: './nutrition-daily-report.component.html',
  styleUrls: ['./nutrition-daily-report.component.scss']
})
export class NutritionDailyReportComponent implements OnInit {
  patientId!: number;
  todayReport: DailyHealthReport | null = null;
  patientProfile: PatientResponseDTO | null = null;
  currentWeightGoal: number = 0;
  last7DaysStats: any[] = [];
  mealsLoggedToday: number = 0;
  expectedMeals: number = 4;
  totalCaloriesLive: number = 0;
  isSyncing: boolean = false;

  constructor(
    private nutritionService: NutritionService,
    private patientService: PatientService,
    private authService: AuthService,
    private lifestyleService: LifestyleService
  ) {}

  ngOnInit(): void {
    this.loadPatientProfile();
  }

  loadPatientProfile(): void {
    this.patientService.getMe().subscribe(profile => {
      this.patientProfile = profile;
      this.patientId = profile.id; // Use correct Patient ID instead of User ID
      
      this.loadTodayReport();
      this.loadHistory();
      this.loadMealsLogged();
      this.loadWeightGoal();
    });
  }

  loadWeightGoal(): void {
    this.lifestyleService.getGoalsByPatientId(this.patientId).subscribe(goals => {
      if (goals && goals.length > 0) {
        // Filter for weight-related goals first, or just take the latest
        const weightGoal = goals
          .filter(g => g.category === GoalCategory.WEIGHT_LOSS || g.category === GoalCategory.WEIGHT_GAIN || g.category === GoalCategory.MAINTENANCE)
          .sort((a, b) => (b.id || 0) - (a.id || 0))[0];
        
        if (weightGoal) {
          this.currentWeightGoal = weightGoal.targetValue;
        } else {
          // Fallback to latest goal
          this.currentWeightGoal = goals.sort((a, b) => (b.id || 0) - (a.id || 0))[0].targetValue;
        }
      }
    });
  }

  loadTodayReport(): void {
    const today = this.getLocalDateString(new Date());
    this.nutritionService.getDailyHealthReport(this.patientId, today).subscribe({
      next: (report) => {
        this.todayReport = report;
        this.updateHistoryWithTodayData();
      },
      error: (err) => {
        if (err.status === 404) {
          console.warn('Today\'s report not yet generated by backend. Using real-time fallback.');
          this.initializeVirtualReport();
        } else {
          console.error('Error fetching today report:', err);
        }
      }
    });
  }

  initializeVirtualReport(): void {
    const target = this.calculateDailyTarget();
    this.todayReport = {
        id: 0,
        patientId: this.patientId,
        patientName: '',
        lifestylePlanId: 0,
        reportDate: this.getLocalDateString(new Date()),
        actualCalories: this.totalCaloriesLive,
        expectedCalories: target,
        calorieDifference: this.totalCaloriesLive - target,
        currentWeight: this.patientProfile?.weight ?? 0,
        goalWeight: this.currentWeightGoal ?? 0,
        weightDifference: (this.patientProfile?.weight ?? 0) - (this.currentWeightGoal ?? 0),
        missedLog: this.totalCaloriesLive === 0,
        anomalyDetected: false,
        anomalies: []
    };
    this.recalculateTodayAnomalies();
    this.updateHistoryWithTodayData();
  }

  calculateDailyTarget(): number {
    if (!this.patientProfile || !this.patientProfile.weight || !this.patientProfile.height) {
      return 2000; // Default fallback
    }

    const weight = this.patientProfile.weight;
    const height = this.patientProfile.height;
    
    let age = 30; // Default
    if (this.patientProfile.birthDate) {
      const birthDate = new Date(this.patientProfile.birthDate);
      const today = new Date();
      age = today.getFullYear() - birthDate.getFullYear();
      const m = today.getMonth() - birthDate.getMonth();
      if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
        age--;
      }
    }

    // Mifflin-St Jeor Equation (matching dashboard)
    let bmr = (10 * weight) + (6.25 * height) - (5 * age);
    if (this.patientProfile.gender === 'MALE') {
      bmr += 5;
    } else {
      bmr -= 161;
    }

    // Light activity multiplier
    return Math.round(bmr * 1.2);
  }

  getLocalDateString(date: Date): string {
    const d = new Date(date);
    let month = '' + (d.getMonth() + 1);
    let day = '' + d.getDate();
    const year = d.getFullYear();
    if (month.length < 2) month = '0' + month;
    if (day.length < 2) day = '0' + day;
    return [year, month, day].join('-');
  }

  loadHistory(): void {
    const today = new Date();
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(today.getDate() - 6);

    const from = this.getLocalDateString(sevenDaysAgo);
    const to = this.getLocalDateString(today);

    this.nutritionService.getHealthReportRange(this.patientId, from, to).subscribe({
      next: (reports) => {
        this.processHistory(reports);
        // If some reports are missing for past days, we could trigger a sync here
      },
      error: (err) => console.error('Error fetching history:', err)
    });
  }

  syncHistory(): void {
    if (this.isSyncing) return;
    this.isSyncing = true;
    
    console.log('Syncing history for last 7 days...');
    const syncTasks = [];
    
    for (let i = 0; i < 7; i++) {
      const d = new Date();
      d.setDate(d.getDate() - i);
      const dateStr = this.getLocalDateString(d);
      syncTasks.push(this.nutritionService.generateDailyReport(this.patientId, dateStr));
    }

    forkJoin(syncTasks).subscribe({
      next: () => {
        console.log('Sync complete');
        this.loadHistory();
        this.isSyncing = false;
      },
      error: (err) => {
        console.error('Sync failed:', err);
        this.isSyncing = false;
      }
    });
  }

  loadMealsLogged(): void {
    const today = this.getLocalDateString(new Date());
    this.nutritionService.getFoodDiary(this.patientId, today).subscribe(entries => {
      this.mealsLoggedToday = entries.length;
      this.totalCaloriesLive = entries.reduce((sum, e) => sum + e.calories, 0);
      
      if (!this.todayReport) {
        this.initializeVirtualReport();
      } else {
        this.todayReport.actualCalories = this.totalCaloriesLive;
        this.todayReport.calorieDifference = this.todayReport.actualCalories - this.todayReport.expectedCalories;
        this.recalculateTodayAnomalies();
        this.updateHistoryWithTodayData();
      }
    });
  }

  recalculateTodayAnomalies(): void {
    if (!this.todayReport) return;

    this.todayReport.missedLog = this.totalCaloriesLive === 0;
    this.todayReport.anomalies = [];
    
    if (this.todayReport.missedLog) {
      this.todayReport.anomalies.push(AnomalyType.MISSED_LOG);
    } else {
      // Logic matching backend thresholds
      if (this.todayReport.calorieDifference > 100) {
        this.todayReport.anomalies.push(AnomalyType.OVEREATING);
      } else if (this.todayReport.calorieDifference < -500) {
        this.todayReport.anomalies.push(AnomalyType.UNDEREATING);
      }
    }
    
    this.todayReport.anomalyDetected = this.todayReport.anomalies.length > 0;
  }

  updateHistoryWithTodayData(): void {
    const todayStr = this.getLocalDateString(new Date());
    const todayIndex = this.last7DaysStats.findIndex(s => s.dateKey === todayStr);
    
    if (todayIndex !== -1) {
      this.last7DaysStats[todayIndex].calories = this.totalCaloriesLive;
      if (this.todayReport) {
        this.last7DaysStats[todayIndex].status = this.formatStatus(this.todayReport);
      }
    }
  }

  private ensureStringDate(date: any): string {
    if (!date) return '';
    if (Array.isArray(date)) {
      const [year, month, day] = date;
      return `${year}-${month.toString().padStart(2, '0')}-${day.toString().padStart(2, '0')}`;
    }
    if (typeof date === 'string') {
      return date.split('T')[0].trim();
    }
    return date.toString();
  }

  processHistory(reports: DailyHealthReport[]): void {
    console.log('Processing history reports:', reports);
    this.last7DaysStats = [];
    
    for (let i = 0; i < 7; i++) {
        const d = new Date();
        d.setDate(d.getDate() - i);
        const dateKey = this.getLocalDateString(d);
        const displayDate = d.toLocaleDateString('en-US', { day: 'numeric', weekday: 'short' });
        
        const report = reports.find(r => {
            const rDate = this.ensureStringDate(r.reportDate);
            // Robust check: normalize both to YYYY-MM-DD
            const match = rDate === dateKey;
            
            // Log first match attempt for each day to debug
            console.log(`[DEBUG] Day ${i}: Comparing reportDate=${rDate} with dateKey=${dateKey} | Match: ${match}`);
            return match;
        });
        
        if (report) {
            this.last7DaysStats.push({
                dateKey: dateKey,
                date: displayDate,
                calories: report.actualCalories,
                status: this.formatStatus(report)
            });
        } else {
            this.last7DaysStats.push({
                dateKey: dateKey,
                date: displayDate,
                calories: dateKey === this.getLocalDateString(new Date()) ? this.totalCaloriesLive : 0,
                status: dateKey === this.getLocalDateString(new Date()) && this.totalCaloriesLive > 0 ? 'OK' : 'MISSED_LOG'
            });
        }
    }

    const sorted = reports.sort((a, b) => new Date(b.reportDate).getTime() - new Date(a.reportDate).getTime());
    if (!this.todayReport && sorted.length > 0) {
      const latest = sorted[0];
      this.todayReport = {
        ...latest,
        id: 0,
        reportDate: this.getLocalDateString(new Date()),
        actualCalories: this.totalCaloriesLive,
        calorieDifference: this.totalCaloriesLive - latest.expectedCalories,
        anomalies: [],
        anomalyDetected: false,
        missedLog: this.totalCaloriesLive === 0
      };
      this.recalculateTodayAnomalies();
    }

    this.updateHistoryWithTodayData();
  }

  formatStatus(r: DailyHealthReport): string {
    // Priority: Eating status over MISSED_LOG if calories exist
    if (r.anomalies && r.anomalies.includes(AnomalyType.OVEREATING)) return 'OVEREATING';
    if (r.anomalies && r.anomalies.includes(AnomalyType.UNDEREATING)) return 'UNDEREATING';
    if (r.missedLog) return 'MISSED_LOG';
    return 'OK';
  }

  get calorieBalance(): number {
    return this.totalConsumedToday - this.dailyCalorieTarget;
  }

  get weightDiff(): number {
    const currentWeight = this.patientProfile?.weight ?? 0;
    const goal = this.weightGoal;
    if (currentWeight === 0 || goal === 0) return 0;
    return currentWeight - goal;
  }

  get totalConsumedToday(): number {
    return this.todayReport?.actualCalories ?? this.totalCaloriesLive;
  }

  get dailyCalorieTarget(): number {
    return this.calculateDailyTarget();
  }

  get weightGoal(): number {
    return this.currentWeightGoal || this.todayReport?.goalWeight || 0;
  }

  hasAnomaly(type: string): boolean {
    if (!this.todayReport || !this.todayReport.anomalies) return false;
    return this.todayReport.anomalies.includes(type as AnomalyType);
  }
}
