import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { PatientService } from '../../../../../services/patient.service';
import { PatientResponseDTO } from '../../../../../models/patient.model';

@Component({
  selector: 'app-patient-record-list',
  templateUrl: './patient-record-list.component.html',
  styleUrls: ['./patient-record-list.component.scss']
})
export class PatientRecordListComponent implements OnInit {
  type: string = '';
  title: string = '';
  data: any[] = [];
  loading: boolean = true;

  constructor(
    private route: ActivatedRoute,
    private patientService: PatientService
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.type = params['type'];
      this.setMetadata();
      this.loadData();
    });
  }

  setMetadata(): void {
    switch (this.type) {
      case 'consultations': 
        this.title = 'Consultation History'; 
        break;
      case 'prescriptions': 
        this.title = 'My Prescriptions'; 
        break;
      case 'treatments': 
        this.title = 'My Treatments'; 
        break;
      case 'diagnoses': 
        this.title = 'My Diagnoses'; 
        break;
      default: 
        this.title = 'Medical Records';
    }
  }

  loadData(): void {
    this.loading = true;
    this.patientService.getMe().subscribe({
      next: (patient: any) => {
        const rawData = patient[this.type] || [];
        // Sort by date if applicable
        this.data = rawData.sort((a: any, b: any) => {
          const dateA = new Date(a.date || a.startDate).getTime();
          const dateB = new Date(b.date || b.startDate).getTime();
          return dateB - dateA;
        });
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  downloadPrescription(item: any): void {
      const content = `
PRESCRIPTION
---------------------------
Date: ${new Date(item.date).toLocaleDateString()}
Medication: ${item.medication}
Dosage: ${item.dosage}
Instructions: ${item.instructions}
---------------------------
Generated by MediaCareAI
      `;
      const blob = new Blob([content], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `prescription_${item.id}.txt`;
      a.click();
      window.URL.revokeObjectURL(url);
  }
}
